import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, IBM_Plex_Serif} from "next/font/google";
import "../styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})
const ibmPlexSerif = IBM_Plex_Serif({
  weight: ["400"],
  variable: "--font-plex-serif",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Horizon",
  description: "Generated by banking platform",
  icons: {
    icon: '/icons/logo.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
